[package]
name = "memory_database"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.9", features = ["luajit"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"